version: 0.0
os: linux
files:
  - source: chef
    destination: /etc/chef/codedeploy/cookbooks/hungry_web_prod
hooks:
  BeforeInstall:
    - location: scripts/install-chef.sh
  AfterInstall:
    - location: scripts/chef-run.sh
      timeout: 800
  ValidateService:
    - location: scripts/validate.sh
      timeout: 3600
      runas: deploy
